services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
parameters:
    fire.test.hostname: '%env(resolve:TEST_URL)%'
    fire.test.https: '%env(resolve:HTTPS)%'